### PR TITLE
Ft read local ical

### PR DESCRIPTION
**Pull request by gsilvapt**

### CODE REVIEW

**Comment by tcarreira** [comment]
Would you add some kind of testing steps? And maybe a `./data/data.json.example`? I'm not sure what to do without having to understand all the code 😄

**Comment by gsilvapt** [comment]
> Would you add some kind of testing steps? 

I believe I can try to do some tests, yes. The structure of the main object is tough though. It's massive and complex so I'm not totally certain how I'll test this. But sure, I can try to do that.

> And maybe a `./data/data.json.example`? I'm not sure what to do without having to understand all the code smile

I actually added this folder to the gitignore. I don't think the actual data should be pushed to the repository for privacy and some other reasons. 

As regarding to what to do, do not forget this piece of code just reads a json file from the host and loads it as a Go structure, nothing else. As for business logic and similar, that has to be worked on from hereon. By the way, this program is expecting that a file called `data.json` exists under `data/`.

**Comment by tcarreira** [comment]
Sorry, I mean manual testing. What do I have to do to play with it.

**Comment by gsilvapt** [comment]
> Sorry, I mean manual testing. What do I have to do to play with it.

For the time being, you cannot do much really. It only imports the file into memory and prints it to the standard output. Nothing fancy yet. To properly work it out, you will need a JSON file that would look similar to the `struct`s provided in the other file.

**Comment by tcarreira** [comment]
I would suggest adding that sample file to the data folder and ignore all other files in `.gitignore`:
```
data/*
!data/data.example.json
```

in the future, if we start importing all files from the data dir, we could move it somewhere else, but as now we are importing it individually, this would work. What do you think?

Or just add that example.json in the readme file. 

What do you think?

**Comment by gsilvapt** [comment]
> I would suggest adding that sample file to the data folder and ignore all other files in `.gitignore`:
> 
> ```
> data/*
> !data/data.example.json
> ```

This is cool, I will add this to the gitignore.

I will add a sample json file without data. or something like that.

**Comment by tcarreira** [comment]
@gsilvapt Do you mind if I close this PR, in favor of #4?

**Pull request closed without merging**
